### ISSUE TITLE
Crash: "Assertion failed at line 91.."

### ISSUE THREAD

**Issue by BrainBurner-o** [KeldorKatarn/OpenTTD_PatchPack#10]
Hello, 

I'm new here and to the patchpack, not new to openttd, but i wanted to try some of the features provided by this pack. After a few years in game I get this error:
Assertion failed at line 91 of c:\users\andreas\documents\visual studio 2015\projects\openttd\src\tile_map.h: tile < MapSize()

I have attached a savegame from just before the crash. 

Thanks in advance for your response

Best regards

Stefan

[Openttd crash savegame.zip](https://github.com/KeldorKatarn/OpenTTD_PatchPack/files/3124856/Openttd.crash.savegame.zip)

**Comment by KeldorKatarn** [comment]
Patch Pack is no longer maintained. Features are migrating to JGR Patch Pack
https://github.com/JGRennison/OpenTTD-patches
