### ISSUE TITLE
Build tram tunnels and bridges with public road module

### ISSUE THREAD

**Issue by MostickP** [KeldorKatarn/OpenTTD_PatchPack#11]
I'm sure you will understand what I mean if you will see screenshot. Please tell how to fix this

![image](https://user-images.githubusercontent.com/59014048/71110676-7189ec80-21d0-11ea-9168-fc01bf82afdc.png)

**Comment by MostickP** [comment]
Well, I don't know is my fix correct or not, but my map generatec correcly after I did change
ROADTYPES_ROAD values into ROADTYPE_ROAD

Hope this is the right fix

**Comment by KeldorKatarn** [comment]
Patch Pack is no longer maintained. Features are migrating to JGR Patch Pack
https://github.com/JGRennison/OpenTTD-patches
