### ISSUE TITLE
Advanced remplacement kick other in multiplayer 

### ISSUE THREAD

**Issue by mushugit** [KeldorKatarn/OpenTTD_PatchPack#2]
In multiplayer when I (as the host) use the new replacement tool as soon as a train enter the depot to be replaced everybody else in the game is disconnected with the message : "WARNING: client x (IP: xxx.xxx.xxx.xxx) tried to execute a command as comany 1, kicking..." I am company 1 and I'm the only one using replacement. Can you look into it ?﻿

**Comment by KeldorKatarn** [comment]
Should be fixed by now.
