### ISSUE TITLE
"Assertion failed at line…" leads to crash

### ISSUE THREAD

**Issue by ghost** [KeldorKatarn/OpenTTD_PatchPack#4]
Hello, I'm not sure if this is a OpenTTD issue (doubt it, can run 1.6.1 totally fine) or an issue with the patch pack specifically, or an issue with my OS setup. 
Either way, I've dealt with crashes randomly as of late in the game (after building up a small network but with lots of vehicles), and usually experience a crash when closing a window or sometimes just randomly.
The main part of the crash is 
`Error: Assertion failed at line 169 of /home/luke/OpenTTD_PatchPack/src/core/pool_type.hpp: pn == Tpool->Get(pn->index)`

Attached also is my crash log.

Sorry if this isn't the right venue.
[crash.log.txt](https://github.com/KeldorKatarn/OpenTTD_PatchPack/files/389732/crash.log.txt)

**Comment by KeldorKatarn** [comment]
Can you provide a savegame for this?

**Comment by ghost** [comment]
That was quite a while ago. It's probably fixed by now. Haven't used this project for a while, and now I cannot compile the latest git pull. I kind of forgot about this issue :( sorry about that.
