### ISSUE TITLE
Failed compilation in linux: /tbtr_template_gui_create_virtualtrain.cpp', needed by 'tbtr_template_gui_create_virtualtrain.o'

### ISSUE THREAD

**Issue by wattsra** [KeldorKatarn/OpenTTD_PatchPack#5]
I have come across this issue when compiling on linux. I cannot seem to work out how best to deal with this, anyone else seen this before? 

Included the specific issue below.

[SRC] Compiling tbtr_template_gui_create.cpp
make[1]: **\* No rule to make target '/home/robert/openttdbuilds/OpenTTD_PatchPack/src/tbtr_template_gui_create_virtualtrain.cpp', needed by 'tbtr_template_gui_create_virtualtrain.o'. Stop.
make[1]: Leaving directory '/home/robert/openttdbuilds/OpenTTD_PatchPack/objs/release'

**Comment by KeldorKatarn** [comment]
I do not support Linux builds. Sorry. But my guess would be that the makefile doesn't add tbtr_template_gui_create_virtualtrain.cpp to the list of compiled files. Maybe add it manually and make a pull request.

**Comment by noahlvb** [comment]
@poloking Have you found a solution yet? I have been having the same trouble.

**Comment by wattsra** [comment]
Unfortunately not. I tried to include the modules that were asked for but
it ended up with more requirement's and more errors that I didn't have time
to investigate.

I went with another patch pack in the end.

I am puzzled at how it even compiles on windows given the ".cpp" isn't
"include"ed anywhere I can see.

**Comment by noahlvb** [comment]
O found out that some off the files are just simply missing that are required to compile on Linux. I am currently working on an solution and I will make a pull request when I am done with it

**Comment by wattsra** [comment]
Great. I'm sure many people will appreciate this.

I found it to be a rabbit hole to find the right files. Hopefully you are
more skilled than I.


On 31 Jan 2017 09:22, "Noah van Bochove" <notifications@github.com> wrote:

O found out that some off the files are just simply missing that are
required to compile on Linux. I am currently working on an solution and I
will make a pull request when I am done with it

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/KeldorKatarn/OpenTTD_PatchPack/issues/5#issuecomment-276313887>,
or mute the thread

**Comment by noahlvb** [comment]
@poloking sorry but I understand what you meant know. I don't have the time to sort this out.

**Comment by wattsra** [comment]
@noahlvb - I forked the code and fixed it for linux in my own repo
