### ISSUE TITLE
Crash in wine

### ISSUE THREAD

**Issue by ecolortest** [KeldorKatarn/OpenTTD_PatchPack#8]
Help, it crash in wine:

Crash log: *** OpenTTD Crash Report ***

Crash at: Tue May 29 02:09:24 2018
In game date: 0-01-00 (0)

Crash reason:
Exception: C0000005
Location: 004DC21E
Message: <none>

OpenTTD version:
Version: - Joker's Patch Pack v1.24.4 (0)
NewGRF ver: 19006d63
Bits: 32
Endian: little
Dedicated: no
Build date: Apr 28 2018 16:03:20

Registers:
EAX: 00000E1F EBX: 0000387C ECX: 00000000 EDX: 00000002
ESI: 000002D3 EDI: 00000002 EBP: 0032E88C ESP: 0032E878
EIP: 004DC21E EFLAGS: 00010297

Bytes at instruction pointer:
8A 43 10 0F B6 D0 3B D7 0F 84 C9 00 00 00 83 FF 02 75 24 85 D2 75 20 39

Stack trace:
00219C88 0000000C 4000004D 00000000 0000003F 00000000 0049F18F 00000000
00000002 00000015 0032E938 00000002 00000000 00000000 00000000 00000000
00000002 00000002 00000015 00000002 0000000C 00000000 00219C68 00000000
0000000B 00130BA0 00000017 00000000 4000004D 0000000A 0049F440 0000000C
0000000B 00000001 00000000 00000000 00000017 00000000 00000002 00219CB8
00000001 00000004 0032E970 00000015 00000002 0032FB28 0086F2D8 00000000
0032F170 0050FBCA 00000002 0032E970 00000000 00000001 00000000 00000000
00203F70 0020F190 0020F190 0032F194 00000000 00000000 4D8A81EE 69737369
6720676E 68706172 00736369 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000

Operating system:
Name: Windows
Release: 5.1.2600 (Service Pack 3)
Compiler: MSVC 1912

Configuration:
Blitter: 32bpp-anim
Graphics set: none (4294967295)
Language: Z:\Users\okansp\Downloads\OpenTTD_LetsPlayEdition_32bit\lang\english_US.lng
Music driver: none
Music set: none (4294967295)
Network: no
Sound driver: none
Sound set: none (4294967295)
Video driver: win32

Fonts:
Small: sprite
Medium: sprite
Large: sprite
Mono: sprite

AI Configuration (local: 0):

Libraries:
FreeType: 2.6.0
ICU i18n: 55.1
ICU lx: 55.1
LZMA: 5.2.1
LZO: 2.09
PNG: 1.6.18
Zlib: 1.2.8

Module information:
Z:\Users\okansp\Downloads\OpenTTD_LetsPlayEdition_32bit\openttd.exe handle: 00400000 size: 13819392 crc: B40E105F date: 2018-04-28 07:07:46
C:\windows\system32\ntdll.dll handle: 7BC10000 size: 2468 crc: FB718EBA date: 2018-04-28 23:35:38
C:\windows\system32\KERNEL32.dll handle: 40AE0000 size: 1677836 crc: 5C7A04F3 date: 2018-04-28 23:35:32
C:\windows\system32\winmm.dll handle: 42850000 size: 475744 crc: ECB2054F date: 2018-04-28 23:35:32
C:\windows\system32\user32.dll handle: 42950000 size: 227780 crc: 941BABED date: 2018-04-28 23:35:35
C:\windows\system32\gdi32.dll handle: 42D40000 size: 16152 crc: 661CC3ED date: 2018-04-28 23:35:34
C:\windows\system32\advapi32.dll handle: 43010000 size: 2488 crc: 72E51CA9 date: 2018-04-28 23:35:36
C:\windows\system32\version.dll handle: 43100000 size: 2484 crc: 9EE4EBDF date: 2018-04-28 23:35:34
C:\windows\system32\ole32.dll handle: 43120000 size: 19576 crc: FFCF05CB date: 2018-04-28 23:35:37
C:\windows\system32\rpcrt4.dll handle: 434A0000 size: 2472 crc: 6810D2D7 date: 2018-04-28 23:35:36
C:\windows\system32\msacm32.dll handle: 435E0000 size: 22744 crc: 56ED9DAA date: 2018-04-28 23:35:34
C:\windows\system32\ws2_32.dll handle: 43630000 size: 2476 crc: 1318FF5D date: 2018-04-28 23:35:35
C:\windows\system32\imm32.dll handle: 436A0000 size: 2468 crc: BE40FCE4 date: 2018-04-28 23:35:33
C:\windows\system32\shell32.dll handle: 436E0000 size: 1416672 crc: 984DAC8F date: 2018-04-28 23:35:36
C:\windows\system32\shlwapi.dll handle: 43AC0000 size: 19932 crc: 83F20744 date: 2018-04-28 23:35:35
C:\windows\system32\comctl32.dll handle: 43BB0000 size: 178076 crc: 4455CF90 date: 2018-04-28 23:35:34
C:\windows\system32\winemac.drv handle: 44000000 size: 1032 crc: 2FE56CE0 date: 2018-04-28 23:35:37
C:\windows\system32\uxtheme.dll handle: 44290000 size: 2448 crc: 9443403E date: 2018-04-28 23:35:38
C:\windows\system32\iphlpapi.dll handle: 45740000 size: 2480 crc: A6A82B86 date: 2018-04-28 23:35:33
C:\windows\system32\psapi.dll handle: 456C0000 size: 2500 crc: AA22BDD2 date: 2018-04-28 23:35:37

---- gamelog start ----
---- gamelog end ----

Command Log:
Showing most recent 0 of 0 commands

*** End of OpenTTD Crash Report ***

Decoded stack trace:
[00] ??? 0x004DC21E

*** End of additional info ***

Device: Mac Book Pro early 2011
OS: MacOs High Sierra Version 10.13.4
CPU: 2.3 GHz Inte; Core i5
Memory: 8GB 1600 MHz DDR3
GPU: Intel HG Grapics 3000 512 MB
Storage: 525 GB Sata SSD

**Comment by KeldorKatarn** [comment]
Wine is not a platform my patch pack supports. But.. as a note.. you're running an outdated version. So you might want to update and check if the problem persists. the 1.24 version range had a couple of issues.
