### ISSUE TITLE
Help not working compile mac

### ISSUE THREAD

**Issue by ecolortest** [KeldorKatarn/OpenTTD_PatchPack#9]
/Users/USER/OpenTTD_PatchPack-master_joker/src/core/container_func.hpp:38:51: error: 
      expected expression
        return container_unordered_remove_if (container, [&](const typen...
                                                                                                 
the probem at [&]

**Comment by wattsra** [comment]
can you provide a little bit more information? How were you compiling, what instructions did you follow? were there any other issues? maybe at configure time? 

Also there are many compile issues with this repo for linux, I fixed them in my fork of this project, it may also help you on Mac.

**Comment by KeldorKatarn** [comment]
Patch Pack is no longer maintained. Features are migrating to JGR Patch Pack
https://github.com/JGRennison/OpenTTD-patches
